SNI_MAPPED = {
    "A": ["01", "02", "03"],
    "B": ["05", "06", "07", "08", "09"],
    "C": [str(i).zfill(2) for i in range(10, 34)],
    "D": ["35"],
    "E": ["36", "37", "38", "39"],
    "F": ["41", "42", "43"],
    "G": ["46", "47"],
    "H": ["49", "50", "51", "52", "53"],
    "I": ["55", "56"],
    "J": ["58", "59", "60"],
    "K": ["61", "62", "63"],
    "L": ["64", "65", "66"],
    "M": ["68"],
    "N": [str(i).zfill(2) for i in range(69, 76)],
    "O": [str(i).zfill(2) for i in range(77, 83)],
    "P": ["84"],
    "Q": ["85"],
    "R": ["86", "87", "88"],
    "S": ["90", "91", "92", "93"],
    "T": ["94", "95", "96"],
    "U": ["97", "98"],
    "V": ["99"],
}

SNI_MAIN = [
    ("A", "Jordbruk, skogsbruk och fiske"),
    ("B", "Utvinning av mineral"),
    ("C", "Tillverkning"),
    ("D", "Försörjning av el, gas, värme och kyla"),
    ("E", "Vattenförsörjning; avloppsrening, avfallshantering och sanering"),
    ("F", "Byggverksamhet"),
    ("G", "Handel"),
    ("H", "Transport och magasinering"),
    ("I", "Hotell- och restaurangverksamhet"),
    ("J", "Förlagsverksamhet, Radio- och TV-sändning och distribution"),
    ("K", "Telekommunikation och dataverksamhet"),
    ("L", "Finansiell verksamhet och försäkring"),
    ("M", "Fastighetsverksamhet"),
    ("N", "Juridik, ekonomi, vetenskap och teknik"),
    ("O", "Uthyrning, fastighetsservice och stödverksamhet"),
    ("P", "Offentlig förvaltning och försvar"),
    ("Q", "Utbildning"),
    ("R", "Vård och omsorg; social verksamhet"),
    ("S", "Kultur, idrott och fritid"),
    ("T", "Annan serviceverksamhet"),
    ("U", "Förvärvsarbete i hushåll"),
    ("V", "Internationella organisationer och ambassader"),
]

SNI_TWO = {
    "01": "Jordbruk och jakt samt stödverksamhet i anslutning härtill",
    "02": "Skogsbruk",
    "03": "Fiske och vattenbruk",
    "05": "Kolutvinning",
    "06": "Utvinning av råpetroleum och naturgas",
    "07": "Utvinning av metallmalmer",
    "08": "Annan utvinning av mineral",
    "09": "Stödverksamhet avseende utvinning",
    "10": "Livsmedelsframställning",
    "11": "Framställning av drycker",
    "12": "Tobaksvarutillverkning",
    "13": "Textilvarutillverkning",
    "14": "Tillverkning av kläder",
    "15": "Tillverkning av läder- och skinnvaror och liknande varor av andra material",
    "16": "Tillverkning av trä och varor av trä och kork, utom möbler",
    "17": "Pappers- och pappersvarutillverkning",
    "18": "Grafisk produktion och reproduktion av inspelningar",
    "19": "Tillverkning av stenkolsprodukter och raffinerade petroleumprodukter",
    "20": "Tillverkning av kemikalier och kemiska produkter",
    "21": "Tillverkning av farmaceutiska basprodukter och läkemedel",
    "22": "Tillverkning av gummi- och plastvaror",
    "23": "Tillverkning av andra icke-metalliska mineraliska produkter",
    "24": "Stål- och metallframställning",
    "25": "Tillverkning av metallvaror utom maskiner och apparater",
    "26": "Tillverkning av datorer, elektronikvaror och optik",
    "27": "Tillverkning av elapparatur",
    "28": "Tillverkning av övriga maskiner",
    "29": "Tillverkning av motorfordon, släpfordon och påhängsvagnar",
    "30": "Tillverkning av andra transportmedel",
    "31": "Tillverkning av möbler",
    "32": "Annan tillverkning",
    "33": "Reparation, underhåll och installation av maskiner och utrustning",
    "35": "El-, gas- och ångförsörjning samt luftkonditionering",
    "36": "Vattenförsörjning",
    "37": "Avloppsrening",
    "38": "Insamling av avfall, återvinning och bortskaffande",
    "39": "Sanering, efterbehandling av jord och vatten samt annan verksamhet för föroreningsbekämpning",
    "41": "Byggande av bostadshus och andra byggnader",
    "42": "Anläggningsarbeten",
    "43": "Specialiserad bygg- och anläggningsverksamhet",
    "46": "Parti- och provisionshandel",
    "47": "Detaljhandel",
    "49": "Landtransport; transport i rörsystem",
    "50": "Sjötransport",
    "51": "Lufttransport",
    "52": "Magasinering, varulagring och stödverksamhet avseende transport",
    "53": "Post- och kurirverksamhet",
    "55": "Hotell- och logiverksamhet",
    "56": "Restaurang-, catering- och barverksamhet",
    "58": "Förlagsverksamhet",
    "59": "Film-, video- och tv-programverksamhet, ljudinspelning och musikutgivning",
    "60": "Planering, radio- och tv-sändning, nyhetsbyråer och annan distribution av medieinnehåll",
    "61": "Telekommunikation",
    "62": "Dataprogrammering, datakonsultverksamhet o.d.",
    "63": "Datainfrastruktur, databehandling, hosting och annan informationsverksamhet",
    "64": "Finansiell verksamhet utom försäkrings- och pensionsfondsverksamhet",
    "65": "Försäkrings-, återförsäkrings- och pensionsfondsverksamhet utom obligatorisk socialförsäkring",
    "66": "Stödverksamhet avseende finansiella tjänster och försäkringsverksamhet",
    "68": "Fastighetsverksamhet",
    "69": "Juridisk och ekonomisk konsultverksamhet",
    "70": "Verksamheter som utövas av huvudkontor samt konsultverksamhet avseende företag",
    "71": "Arkitekt- och teknisk konsultverksamhet; teknisk provning och analys",
    "72": "Vetenskaplig forskning och utveckling",
    "73": "Reklamverksamhet, marknadsundersökningar och PR",
    "74": "Annan verksamhet inom juridik, ekonomi, vetenskap och teknik",
    "75": "Veterinärverksamhet",
    "77": "Uthyrning och leasing",
    "78": "Arbetsförmedling, bemanning och annan personalrelaterad verksamhet",
    "79": "Resebyrå- och researrangörsverksamhet samt annan boknings- och reserelaterad verksamhet",
    "80": "Säkerhets- och bevakningsverksamhet",
    "81": "Fastighetsrelaterad stödverksamhet samt skötsel och underhåll av grönytor",
    "82": "Kontorstjänster och annan stödverksamhet till företag",
    "84": "Offentlig förvaltning och försvar; obligatorisk socialförsäkring",
    "85": "Utbildning",
    "86": "Hälso- och sjukvård",
    "87": "Vård och omsorg med boende",
    "88": "Öppna sociala insatser",
    "90": "Konstnärligt skapande och scenkonst",
    "91": "Biblioteks-, arkiv- och museiverksamhet m.m.",
    "92": "Spel- och vadhållningsverksamhet",
    "93": "Sport-, fritids- och nöjesverksamhet",
    "94": "Intressebevakning; religiös verksamhet",
    "95": "Reparation och underhåll av datorer, hushållsartiklar och varor för personligt bruk samt motorfordon och motorcyklar",
    "96": "Konsumenttjänster",
    "97": "Förvärvsarbete i hushåll",
    "98": "Hushållens produktion av diverse varor och tjänster för eget bruk",
    "99": "Verksamhet vid internationella organisationer, utländska ambassader o.d.",
}
##Not used
# ~ MINING_REQUEST_TYPE = [
    # ~ ("industry", "Industry"),
    # ~ ("lista/omsatter-mest/11", "Turns over the most"),
    # ~ ("lista/hogst-resultat/12", "Highest result"),
    # ~ ("lista/storsta-arbetsgivarna/13", "Largest employers"),
    # ~ ("lista/flest-bilar/14", "Most cars"),
    # ~ ("lista/bolag-med-varumarken/15", "Companies with brands"),
    # ~ ("lista/bostads-och-bostadsrattfor/25", "Housing Cooperatives"),
    # ~ ("lista/statliga-och-kommunala-bolag/33", "State and Municipal Companies"),
# ~ ]

MINING_CORPORATE_FORM = [
    ("AB", "Aktiebolag"),
    ("Bankaktiebolag", "Bankaktiebolag"),
    ("Europabolag", "Europabolag"),
    ("Försäkringsaktiebolag", "Försäkringsaktiebolag"),
    ("Medlemsbank", "Medlemsbank"),
    ("Publikt aktiebolag", "Publikt aktiebolag"),
    ("Publikt bankaktiebolag", "Publikt bankaktiebolag"),
    ("Publikt försäkringsaktiebolag", "Publikt försäkringsaktiebolag"),
    ("Sparbank", "Sparbank"),
    ("Tjänstepensionsaktiebolag", "Tjänstepensionsaktiebolag"),
    ("Utländsk banks filial", "Utländsk banks filial"),
    ("Ömsesidigt försäkringsbolag", "Ömsesidigt försäkringsbolag"),
    ("Ömsesidigt tjänstepensionsbolag", "Ömsesidigt tjänstepensionsbolag"),
    ("OVR", "Övriga bolagsformer"),
    ("Allmänna försäkringskassor", "Allmänna försäkringskassor"),
    ("Arbetslöshetskassa", "Arbetslöshetskassa"),
    ("Bostadsförening", "Bostadsförening"),
    ("Bostadsrättsförening", "Bostadsrättsförening"),
    ("Ekonomisk förening", "Ekonomisk förening"),
    ("Enkelt bolag", "Enkelt bolag"),
    ("Europakooperativ", "Europakooperativ"),
    (
        "Europeiska Grupperingar för Territoriellt Samarbete (EGTS)",
        "Europeiska Grupperingar för Territoriellt Samarbete (EGTS)",
    ),
    ("Familjestiftelser", "Familjestiftelser"),
    ("Filial", "Filial"),
    ("Försäkringsförening", "Försäkringsförening"),
    ("Hypoteksförening", "Hypoteksförening"),
    ("Ideell förening", "Ideell förening"),
    ("Juridisk form ej utredd", "Juridisk form ej utredd"),
    ("Kommun", "Kommun"),
    ("Kommunförbund", "Kommunförbund"),
    ("Kooperativ hyresrättsförening", "Kooperativ hyresrättsförening"),
    ("Landsting", "Landsting"),
    (
        "Offentliga korporationer och anstalter",
        "Offentliga korporationer och anstalter",
    ),
    ("Oskiftat dödsbo", "Oskiftat dödsbo"),
    ("Partrederi", "Partrederi"),
    ("Regional statlig myndighet", "Regional statlig myndighet"),
    ("Registrerat trossamfund", "Registrerat trossamfund"),
    ("Sambruksförening", "Sambruksförening"),
    ("Samfällighet", "Samfällighet"),
    ("Statlig enhet", "Statlig enhet"),
    ("Tjänstepensionsförening", "Tjänstepensionsförening"),
    (
        "Understödsföreningar och försäkringsföreningar",
        "Understödsföreningar och försäkringsföreningar",
    ),
    ("Utländsk juridisk person", "Utländsk juridisk person"),
    ("Värdepappersfonder", "Värdepappersfonder"),
    ("Övriga stiftelser eller fonder", "Övriga stiftelser eller fonder"),
    (
        "Övriga svenska juridiska personer bildade enligt särskild lagstiftning",
        "Övriga svenska juridiska personer bildade enligt särskild lagstiftning",
    ),
    ("EF", "Enskild näringsidkare"),
    ("HB/KB", "Handelsbolag eller kommanditbolag"),
    ("Gruvbolag", "Gruvbolag"),
    ("Handelsbolag", "Handelsbolag"),
    ("Kommanditbolag", "Kommanditbolag"),
]

MINING_LAN = [
    ("Blekinge", "Blekinge"),
    ("Dalarna", "Dalarna"),
    ("Gotland", "Gotland"),
    ("Gävleborg", "Gävleborg"),
    ("Halland", "Halland"),
    ("Jämtland", "Jämtland"),
    ("Jönköping", "Jönköping"),
    ("Kalmar", "Kalmar"),
    ("Kronoberg", "Kronoberg"),
    ("Norrbotten", "Norrbotten"),
    ("Skåne", "Skåne"),
    ("Stockholm", "Stockholm"),
    ("Södermanland", "Södermanland"),
    ("Uppsala", "Uppsala"),
    ("Värmland", "Värmland"),
    ("Västerbotten", "Västerbotten"),
    ("Västernorrland", "Västernorrland"),
    ("Västmanland", "Västmanland"),
    ("Västra Götaland", "Västra Götaland"),
    ("Örebro", "Örebro"),
    ("Östergötland", "Östergötland"),
]

MINING_KOMMUN = [
    ("Hällefors", "Hällefors"),
    ("Skövde", "Skövde"),
    ("Eskilstuna", "Eskilstuna"),
    ("Vindeln", "Vindeln"),
    ("Stenungsund", "Stenungsund"),
    ("Nora", "Nora"),
    ("Timrå", "Timrå"),
    ("Lysekil", "Lysekil"),
    ("Nordanstig", "Nordanstig"),
    ("Trollhättan", "Trollhättan"),
    ("Höör", "Höör"),
    ("Färgelanda", "Färgelanda"),
    ("Piteå", "Piteå"),
    ("Skara", "Skara"),
    ("Järfälla", "Järfälla"),
    ("Lessebo", "Lessebo"),
    ("Habo", "Habo"),
    ("Östra Göinge", "Östra Göinge"),
    ("Vaxholm", "Vaxholm"),
    ("Sala", "Sala"),
    ("Degerfors", "Degerfors"),
    ("Sollentuna", "Sollentuna"),
    ("Ludvika", "Ludvika"),
    ("Uddevalla", "Uddevalla"),
    ("Falköping", "Falköping"),
    ("Hedemora", "Hedemora"),
    ("Laholm", "Laholm"),
    ("Åtvidaberg", "Åtvidaberg"),
    ("Lund", "Lund"),
    ("Sundbyberg", "Sundbyberg"),
    ("Härjedalen", "Härjedalen"),
    ("Karlstad", "Karlstad"),
    ("Gnosjö", "Gnosjö"),
    ("Svedala", "Svedala"),
    ("Malå", "Malå"),
    ("Strömsund", "Strömsund"),
    ("Landskrona", "Landskrona"),
    ("Åmål", "Åmål"),
    ("Borås", "Borås"),
    ("Fagersta", "Fagersta"),
    ("Falun", "Falun"),
    ("Kristianstad", "Kristianstad"),
    ("Surahammar", "Surahammar"),
    ("Högsby", "Högsby"),
    ("Vansbro", "Vansbro"),
    ("Umeå", "Umeå"),
    ("Norsjö", "Norsjö"),
    ("Jokkmokk", "Jokkmokk"),
    ("Örnsköldsvik", "Örnsköldsvik"),
    ("Upplands Väsby", "Upplands Väsby"),
    ("Övertorneå", "Övertorneå"),
    ("Bollebygd", "Bollebygd"),
    ("Östersund", "Östersund"),
    ("Pajala", "Pajala"),
    ("Vetlanda", "Vetlanda"),
    ("Kristinehamn", "Kristinehamn"),
    ("Södertälje", "Södertälje"),
    ("Ljusdal", "Ljusdal"),
    ("Ängelholm", "Ängelholm"),
    ("Vårgårda", "Vårgårda"),
    ("Kungsör", "Kungsör"),
    ("Tranemo", "Tranemo"),
    ("Munkfors", "Munkfors"),
    ("Sundsvall", "Sundsvall"),
    ("Orsa", "Orsa"),
    ("Göteborg", "Göteborg"),
    ("Ekerö", "Ekerö"),
    ("Eksjö", "Eksjö"),
    ("Vingåker", "Vingåker"),
    ("Norrköping", "Norrköping"),
    ("Nässjö", "Nässjö"),
    ("Ovanåker", "Ovanåker"),
    ("Ydre", "Ydre"),
    ("Säffle", "Säffle"),
    ("Emmaboda", "Emmaboda"),
    ("Kil", "Kil"),
    ("Ödeshög", "Ödeshög"),
    ("Värnamo", "Värnamo"),
    ("Töreboda", "Töreboda"),
    ("Arvidsjaur", "Arvidsjaur"),
    ("Flen", "Flen"),
    ("Grums", "Grums"),
    ("Arjeplog", "Arjeplog"),
    ("Ronneby", "Ronneby"),
    ("Ljusnarsberg", "Ljusnarsberg"),
    ("Kinda", "Kinda"),
    ("Tranås", "Tranås"),
    ("Ulricehamn", "Ulricehamn"),
    ("Trelleborg", "Trelleborg"),
    ("Hofors", "Hofors"),
    ("Norrtälje", "Norrtälje"),
    ("Oxelösund", "Oxelösund"),
    ("Västerås", "Västerås"),
    ("Sandviken", "Sandviken"),
    ("Åre", "Åre"),
    ("Götene", "Götene"),
    ("Sollefteå", "Sollefteå"),
    ("Hylte", "Hylte"),
    ("Gällivare", "Gällivare"),
    ("Lycksele", "Lycksele"),
    ("Skellefteå", "Skellefteå"),
    ("Motala", "Motala"),
    ("Knivsta", "Knivsta"),
    ("Kungsbacka", "Kungsbacka"),
    ("Markaryd", "Markaryd"),
    ("Kiruna", "Kiruna"),
    ("Gagnef", "Gagnef"),
    ("Vallentuna", "Vallentuna"),
    ("Oskarshamn", "Oskarshamn"),
    ("Simrishamn", "Simrishamn"),
    ("Linköping", "Linköping"),
    ("Partille", "Partille"),
    ("Kävlinge", "Kävlinge"),
    ("Heby", "Heby"),
    ("Dorotea", "Dorotea"),
    ("Vännäs", "Vännäs"),
    ("Nynäshamn", "Nynäshamn"),
    ("Vilhelmina", "Vilhelmina"),
    ("Karlshamn", "Karlshamn"),
    ("Katrineholm", "Katrineholm"),
    ("Kalix", "Kalix"),
    ("Sölvesborg", "Sölvesborg"),
    ("Bjurholm", "Bjurholm"),
    ("Alvesta", "Alvesta"),
    ("Haparanda", "Haparanda"),
    ("Svalöv", "Svalöv"),
    ("Västervik", "Västervik"),
    ("Alingsås", "Alingsås"),
    ("Bengtsfors", "Bengtsfors"),
    ("Filipstad", "Filipstad"),
    ("Ystad", "Ystad"),
    ("Lidingö", "Lidingö"),
    ("Älvdalen", "Älvdalen"),
    ("Årjäng", "Årjäng"),
    ("Köping", "Köping"),
    ("Trosa", "Trosa"),
    ("Sjöbo", "Sjöbo"),
    ("Osby", "Osby"),
    ("Ockelbo", "Ockelbo"),
    ("Hässleholm", "Hässleholm"),
    ("Växjö", "Växjö"),
    ("Torsby", "Torsby"),
    ("Aneby", "Aneby"),
    ("Håbo", "Håbo"),
    ("Lindesberg", "Lindesberg"),
    ("Värmdö", "Värmdö"),
    ("Gnesta", "Gnesta"),
    ("Strängnäs", "Strängnäs"),
    ("Tomelilla", "Tomelilla"),
    ("Härryda", "Härryda"),
    ("Nybro", "Nybro"),
    ("Vänersborg", "Vänersborg"),
    ("Rättvik", "Rättvik"),
    ("Säter", "Säter"),
    ("Sotenäs", "Sotenäs"),
    ("Burlöv", "Burlöv"),
    ("Eda", "Eda"),
    ("Helsingborg", "Helsingborg"),
    ("Bräcke", "Bräcke"),
    ("Huddinge", "Huddinge"),
    ("Nacka", "Nacka"),
    ("Boxholm", "Boxholm"),
    ("Örkelljunga", "Örkelljunga"),
    ("Hörby", "Hörby"),
    ("Grästorp", "Grästorp"),
    ("Salem", "Salem"),
    ("Mjölby", "Mjölby"),
    ("Haninge", "Haninge"),
    ("Luleå", "Luleå"),
    ("Mark", "Mark"),
    ("Olofström", "Olofström"),
    ("Hallstahammar", "Hallstahammar"),
    ("Strömstad", "Strömstad"),
    ("Sunne", "Sunne"),
    ("Karlskoga", "Karlskoga"),
    ("Hammarö", "Hammarö"),
    ("Valdemarsvik", "Valdemarsvik"),
    ("Kumla", "Kumla"),
    ("Åsele", "Åsele"),
    ("Laxå", "Laxå"),
    ("Sävsjö", "Sävsjö"),
    ("Vadstena", "Vadstena"),
    ("Mariestad", "Mariestad"),
    ("Skurup", "Skurup"),
    ("Vaggeryd", "Vaggeryd"),
    ("Östhammar", "Östhammar"),
    ("Botkyrka", "Botkyrka"),
    ("Arvika", "Arvika"),
    ("Staffanstorp", "Staffanstorp"),
    ("Överkalix", "Överkalix"),
    ("Nordmaling", "Nordmaling"),
    ("Gävle", "Gävle"),
    ("Leksand", "Leksand"),
    ("Lilla Edet", "Lilla Edet"),
    ("Vara", "Vara"),
    ("Orust", "Orust"),
    ("Hagfors", "Hagfors"),
    ("Forshaga", "Forshaga"),
    ("Mullsjö", "Mullsjö"),
    ("Svenljunga", "Svenljunga"),
    ("Varberg", "Varberg"),
    ("Sorsele", "Sorsele"),
    ("Malmö", "Malmö"),
    ("Karlskrona", "Karlskrona"),
    ("Norberg", "Norberg"),
    ("Borlänge", "Borlänge"),
    ("Mölndal", "Mölndal"),
    ("Hallsberg", "Hallsberg"),
    ("Nyköping", "Nyköping"),
    ("Ale", "Ale"),
    ("Storfors", "Storfors"),
    ("Bollnäs", "Bollnäs"),
    ("Hudiksvall", "Hudiksvall"),
    ("Borgholm", "Borgholm"),
    ("Storuman", "Storuman"),
    ("Boden", "Boden"),
    ("Essunga", "Essunga"),
    ("Tingsryd", "Tingsryd"),
    ("Lidköping", "Lidköping"),
    ("Enköping", "Enköping"),
    ("Öckerö", "Öckerö"),
    ("Torsås", "Torsås"),
    ("Munkedal", "Munkedal"),
    ("Ljungby", "Ljungby"),
    ("Hultsfred", "Hultsfred"),
    ("Vimmerby", "Vimmerby"),
    ("Tidaholm", "Tidaholm"),
    ("Falkenberg", "Falkenberg"),
    ("Arboga", "Arboga"),
    ("Sigtuna", "Sigtuna"),
    ("Gullspång", "Gullspång"),
    ("Vellinge", "Vellinge"),
    ("Mörbylånga", "Mörbylånga"),
    ("Eslöv", "Eslöv"),
    ("Bjuv", "Bjuv"),
    ("Ånge", "Ånge"),
    ("Tyresö", "Tyresö"),
    ("Hjo", "Hjo"),
    ("Upplands-Bro", "Upplands-Bro"),
    ("Robertsfors", "Robertsfors"),
    ("Tanum", "Tanum"),
    ("Mönsterås", "Mönsterås"),
    ("Halmstad", "Halmstad"),
    ("Tierp", "Tierp"),
    ("Kramfors", "Kramfors"),
    ("Gislaved", "Gislaved"),
    ("Söderköping", "Söderköping"),
    ("Lomma", "Lomma"),
    ("Finspång", "Finspång"),
    ("Malung-Sälen", "Malung-Sälen"),
    ("Mellerud", "Mellerud"),
    ("Avesta", "Avesta"),
    ("Lekeberg", "Lekeberg"),
    ("Höganäs", "Höganäs"),
    ("Smedjebacken", "Smedjebacken"),
    ("Båstad", "Båstad"),
    ("Söderhamn", "Söderhamn"),
    ("Älmhult", "Älmhult"),
    ("Mora", "Mora"),
    ("Nykvarn", "Nykvarn"),
    ("Perstorp", "Perstorp"),
    ("Österåker", "Österåker"),
    ("Karlsborg", "Karlsborg"),
    ("Täby", "Täby"),
    ("Dals-Ed", "Dals-Ed"),
    ("Danderyd", "Danderyd"),
    ("Älvkarleby", "Älvkarleby"),
    ("Berg", "Berg"),
    ("Härnösand", "Härnösand"),
    ("Lerum", "Lerum"),
    ("Klippan", "Klippan"),
    ("Solna", "Solna"),
    ("Tibro", "Tibro"),
    ("Älvsbyn", "Älvsbyn"),
    ("Krokom", "Krokom"),
    ("Skinnskatteberg", "Skinnskatteberg"),
    ("Uppvidinge", "Uppvidinge"),
    ("Kungälv", "Kungälv"),
    ("Tjörn", "Tjörn"),
    ("Herrljunga", "Herrljunga"),
    ("Ragunda", "Ragunda"),
    ("Åstorp", "Åstorp"),
    ("Askersund", "Askersund"),
    ("Bromölla", "Bromölla"),
]

# repetition of variable, not sure which one to keep
# MINING_CORPORATE_FORM = [
#     ("xb/EF", "Enskild firma"),
#     ("xb/AB", "Aktiebolag"),
#     ("xb/IF", "Ideella föreningar"),
#     ("xb/HK", "Hb & Kb"),
#     ("xb/OV", "Övriga bolagsformer"),
#     ("xb/SA", "Samfälligheter"),
#     ("xb/SF", "Sambruksförening"),
#     ("xb/FI", "Filialer"),
#     ("xb/EK", "Ekonomisk förening"),
#     ("xb/EB", "Enkla bolag"),
#     ("xb/SK", "Statliga & kommunala"),
#     ("xb/BF", "Bostadsförening"),
#     ("xb/VP", "Värdepappersfonder"),
# ]

MINING_INDUSTRY = [
    (
        "bransch/ambassader-internationella-org/29/_",
        "Ambassader & Internationella Org.",
    ),
    ("bransch/avlopp-avfall-el-vatten/5/_", "Avlopp, Avfall, El & Vatten"),
    ("bransch/bank-finans-forsakring/14/_", "Bank, Finans & Försäkring"),
    ("bransch/bemanning-arbetsformedling/23/_", "Bemanning & Arbetsförmedling"),
    ("branschbransch-arbetsgivar-yrkesorg/27/_", "Bransch-, Arbetsgivar- & Yrkesorg."),
    (
        "bransch/bygg-design-inredningsverksamhet/6/_",
        "Bygg-, Design- & Inredningsverksamhet",
    ),
    ("bransch/data-it-telekommunikation/13/_", "Data, It & Telekommunikation"),
    ("bransch/detaljhandel/9/_", "Detaljhandel"),
    ("bransch/fastighetsverksamhet/15/_", "Fastighetsverksamhet"),
    ("bransch/foretagstjanster/11/_", "Företagstjänster"),
    ("bransch/hotell-restaurang/12/_", "Hotell & Restaurang"),
    ("bransch/har-skonhetsvard/28/_", "Hår & Skönhetsvård"),
    ("bransch/halsa-sjukvard/21/_", "Hälsa & Sjukvård"),
    (
        "bransch/jordbruk-skogsbruk-jakt-fiske/0/_",
        "Jordbruk, Skogsbruk, Jakt & Fiske",
    ),
    (
        "bransch/juridik-ekonomi-konsulttjanster/16/_",
        "Juridik, Ekonomi & Konsulttjänster",
    ),
    ("bransch/kultur-noje-fritid/26/_", "Kultur, Nöje & Fritid"),
    ("bransch/livsmedelsframstallning/2/_", "Livsmedelsframställning"),
    ("bransch/media/3/_", "Media"),
    ("bransch/motorfordonshandel/7/_", "Motorfordonshandel"),
    (
        "bransch/offentlig-forvaltning-samhalle/25/_",
        "Offentlig Förvaltning & Samhälle",
    ),
    ("bransch/partihandel/8/_", "Partihandel"),
    (
        "bransch/reklam-pr-marknadsundersokning/17/_",
        "Reklam, Pr & Marknadsundersökning",
    ),
    ("bransch/reparation-installation/4/_", "Reparation & Installation"),
    ("bransch/resebyra-turism/24/_", "Resebyrå & Turism"),
    ("bransch/teknisk-konsultverksamhet/18/_", "Teknisk Konsultverksamhet"),
    ("bransch/tillverkning-industri/1/_", "Tillverkning & Industri"),
    ("bransch/transport-magasinering/10/_", "Transport & Magasinering"),
    (
        "bransch/utbildning-forskning-utveckling/19/_",
        "Utbildning, Forskning & Utveckling",
    ),
    ("bransch/uthyrning-leasing/22/_", "Uthyrning & Leasing"),
    ("bransch/ovriga-konsumenttjanster/20/_", "Övriga Konsumenttjänster"),
]

MINING_INDUSTRY_XV = [
    ("xv/PARTIHANDEL", "Partihandel"),
    ("xv/JORDBRUK, SKOGSBRUK, JAKT & FISKE", "Jordbruk, skogsbruk, jakt & fiske"),
    ("xv/FASTIGHETSVERKSAMHET", "Fastighetsverksamhet"),
    ("xv/BRANSCH-, ARBETSGIVAR- & YRKESORG.", "Bransch-, arbetsgivar- & yrkesorg."),
    (
        "xv/BYGG-, DESIGN- & INREDNINGSVERKSAMHET",
        "Bygg-, design- & inredningsverksamhet",
    ),
    ("xv/KULTUR, NÖJE & FRITID", "Kultur, nöje & fritid"),
    (
        "xv/JURIDIK, EKONOMI & KONSULTTJÄNSTER",
        "Juridik, ekonomi & konsulttjänster",
    ),
    ("xv/DETALJHANDEL", "Detaljhandel"),
    ("xv/DATA, IT & TELEKOMMUNIKATION", "Data, it & telekommunikation"),
    ("xv/PARTIHANDEL", "Partihandel"),
    ("xv/HÄLSA & SJUKVÅRD", "Hälsa & sjukvård"),
    ("xv/TILLVERKNING & INDUSTRI", "Tillverkning & industri"),
    ("xv/BANK, FINANS & FÖRSÄKRING", "Bank, finans & försäkring"),
    ("xv/UTBILDNING, FORSKNING & UTVECKLING", "Utbildning, forskning & utveckling"),
    ("xv/HOTELL & RESTAURANG", "Hotell & restaurang"),
    ("xv/TRANSPORT & MAGASINERING", "Transport & magasinering"),
    ("xv/TEKNISK KONSULTVERKSAMHET", "Teknisk konsultverksamhet"),
    ("xv/REPARATION & INSTALLATION", "Reparation & installation"),
    ("xv/HÅR & SKÖNHETSVÅRD", "Hår & skönhetsvård"),
    ("xv/ÖVRIGA KONSUMENTTJÄNSTER", "Övriga konsumenttjänster"),
    ("xv/FÖRETAGSTJÄNSTER", "Företagstjänster"),
    ("xv/MEDIA", "Media"),
    ("xv/REKLAM, PR & MARKNADSUNDERSÖKNING", "Reklam, pr & marknadsundersökning"),
    ("xv/BEMANNING & ARBETSFÖRMEDLING", "Bemanning & arbetsförmedling"),
    ("xv/MOTORFORDONSHANDEL", "Motorfordonshandel"),
    ("xv/UTHYRNING & LEASING", "Uthyrning & leasing"),
    ("xv/AVLOPP, AVFALL, EL & VATTEN", "Avlopp, avfall, el & vatten"),
    ("xv/LIVSMEDELSFRAMSTÄLLNING", "Livsmedelsframställning"),
    ("xv/RESEBYRÅ & TURISM", "Resebyrå & turism"),
    ("xv/OFFENTLIG FÖRVALTNING & SAMHÄLLE", "Offentlig förvaltning & samhälle"),
    ("xv/AMBASSADER & INTERNATIONELLA ORG.", "Ambassader & internationella org."),
]

SORT_OPTIONS = [
    ('companyNameAsc', 'Företagsnamn A-Ö'),
    ('naceIndustryName', 'SNI-kod'),
    ('numEmployeesAsc', 'Anställda stigande'),
    ('numEmployeesDesc', 'Anställda fallande'),
    ('postNumber', 'Postnr.'),
    ('profitAsc', 'Resultat stigande'),
    ('profitDesc', 'Resultat fallande'),
    ('registrationDateAsc', 'Registrerad datum stigande'),
    ('registrationDateDesc', 'Registrerad datum fallande'),
    ('relevance', 'Relevans'),
    ('revenueAsc', 'Omsättning stigande'),
    ('revenueDesc', 'Omsättning fallande'),
]
